-- ============================================================================
--  Push-bildirishnoma infratuzilmasi (FCM worker uchun).
--
--  ESLATMA (arxitektura): bu loyihada buyurtmalar alohida relational `orders`
--  jadvalida emas, `app_state` KV jadvalidagi `lume_orders` kaliti ostida JSONB
--  massiv sifatida saqlanadi. Shu sabab "orders.push_sent" ustuni o'rniga
--  push yuborilgan buyurtmalarni belgilash uchun alohida `pushed_orders`
--  dedupe jadvali ishlatiladi (worker app_state'ni polling qiladi).
--
--  Worker Postgres'ga TO'G'RIDAN-TO'G'RI (postgres roli) ulanadi va RLS'ni
--  chetlab o'tadi. Ilova va admin panel esa anon kalit (PostgREST) orqali
--  ishlaydi — shuning uchun quyida anon rolga kerakli ruxsatlar beriladi.
-- ============================================================================

-- --------------------------------------------------------------------------
-- 1) Qurilma FCM tokenlari
-- --------------------------------------------------------------------------
create table if not exists user_push_tokens (
  user_id    text not null,
  token      text not null,
  platform   text,                         -- 'android' | 'ios'
  updated_at timestamptz not null default now(),
  primary key (token)                      -- bitta token = bitta qurilma
);

create index if not exists idx_user_push_tokens_user
  on user_push_tokens (user_id);

-- --------------------------------------------------------------------------
-- 2) Bildirishnomalar (admin broadcast yoki tizim xabari)
-- --------------------------------------------------------------------------
create table if not exists notifications (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text not null default '',
  type       text not null default 'broadcast',  -- 'broadcast' | 'order' | ...
  order_id   text,                               -- ixtiyoriy (order bilan bog'liq bo'lsa)
  created_at timestamptz not null default now(),
  processed  boolean not null default false      -- worker qayta ishladimi
);

create index if not exists idx_notifications_processed
  on notifications (processed) where processed = false;

-- --------------------------------------------------------------------------
-- 3) Har bir foydalanuvchiga tegishli bildirishnoma holati (o'qildi/yo'q)
-- --------------------------------------------------------------------------
create table if not exists user_notifications (
  user_id         text not null,
  notification_id bigint not null references notifications (id) on delete cascade,
  is_read         boolean not null default false,
  created_at      timestamptz not null default now(),
  primary key (user_id, notification_id)
);

create index if not exists idx_user_notifications_user_unread
  on user_notifications (user_id) where is_read = false;

-- --------------------------------------------------------------------------
-- 4) Push yuborilgan buyurtmalar (KV `lume_orders` uchun dedupe)
--    orders alohida jadval bo'lmagani uchun push_sent shu yerda saqlanadi.
--    Faqat worker (postgres roli) yozadi — anon ruxsati berilmaydi.
-- --------------------------------------------------------------------------
create table if not exists pushed_orders (
  order_id text primary key,
  sent_at  timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- RLS + anon ruxsatlari (app_state bilan bir xil ochiq do'kon modeli)
-- --------------------------------------------------------------------------
alter table user_push_tokens  enable row level security;
alter table notifications     enable row level security;
alter table user_notifications enable row level security;
alter table pushed_orders     enable row level security;

-- Ilova o'z tokenini yozadi/yangilaydi.
drop policy if exists "anon full access on user_push_tokens" on user_push_tokens;
create policy "anon full access on user_push_tokens"
  on user_push_tokens for all to anon using (true) with check (true);

-- Ilova bildirishnomalarni o'qiydi; admin panel INSERT qiladi.
drop policy if exists "anon full access on notifications" on notifications;
create policy "anon full access on notifications"
  on notifications for all to anon using (true) with check (true);

-- Ilova o'z yozuvlarini o'qiydi va is_read=true qiladi.
drop policy if exists "anon full access on user_notifications" on user_notifications;
create policy "anon full access on user_notifications"
  on user_notifications for all to anon using (true) with check (true);

-- pushed_orders — anon uchun ruxsat YO'Q (faqat worker to'g'ridan-to'g'ri yozadi).

-- Jadval/ketma-ketlik grantlari (PostgREST anon ishlashi uchun).
grant usage on schema public to anon;
grant select, insert, update, delete on user_push_tokens  to anon;
grant select, insert, update, delete on notifications      to anon;
grant select, insert, update, delete on user_notifications to anon;
grant usage, select on all sequences in schema public to anon;

-- --------------------------------------------------------------------------
-- Trigger: yangi notification qo'shilsa, worker'ga LISTEN/NOTIFY orqali xabar
-- (broadcast'lar deyarli real vaqtda yuboriladi; orders esa polling bilan).
-- --------------------------------------------------------------------------
create or replace function notify_new_notification() returns trigger
language plpgsql as $$
begin
  perform pg_notify('new_notification', new.id::text);
  return new;
end;
$$;

drop trigger if exists trg_new_notification on notifications;
create trigger trg_new_notification
  after insert on notifications
  for each row execute function notify_new_notification();
